### ISSUE TITLE
Create a tag before creating release

### ISSUE THREAD

**Issue by DamirPorobic** [ncipollo/release-action#106]
Hello, I'm currently migrating my Pipeline from Travis-CI to GitHub Action and run across this action for creating releases.
I was wondering if it's possible, for untagged commits, to create a tag or to be more precise, move an existing tag. I have a "continuous" tag that points to my last commit, after the pipeline finishes the artifacts are uploaded to a release that represents that tag. On the next push, the "continuous" tag is moved to a new hash, the old release is deleted and a new release is created where all artifacts are uploaded again. Because multiple jobs create such artifacts, the release can only be created once per commit.
Is it possible to implement such a scenario with this action?

**Comment by ncipollo** [comment]
Hi!,

I'm not sure I completely understand your workflow, but generally I think you could accomplish this by moving the tag (`git tag -f <tag>` and pushing it (`git push -f origin <tag>`). Then you could configure the workflow to run on any tag update (see the sample workflow in the readme). If you set `allowUpdates` to true then the action will update the existing release.

Closing this issue out, if you have additional questions or comments please use the discussion page associated with this repo.
