### ISSUE TITLE
Allow all artifacts to be removed before updating release

### ISSUE THREAD

**Issue by Rosalie241** [ncipollo/release-action#108]
**Is your feature request related to a problem? Please describe.**
I want to be able to have 1 release for github actions where my artifacts have a different filename each time the action is run.
Right now it just keeps adding artifacts to the same release, see https://github.com/Rosalie241/GLideN64/releases/tag/github-actions

**Describe the solution you'd like**
An option which'd remove *all* artifacts from the release before uploading the artifacts would be perfect.
I'm not really familiar with typescript/javascript (hence why I didn't open a PR) but I think something like this code should work?
```typescript
private async deleteArtifactsFromRelease(releaseId: number): Promise<void> {
    const releaseAssets = await this.releases.listArtifactsForRelease(releaseId)
    for (const artifact of releaseAssets) {
        core.debug(`Deleting existing artifact ${artifact.name}...`)
        await this.releases.deleteArtifact(artifact.id)
    }
}
```

**Describe alternatives you've considered**
I've considered keeping the filename the same but that isn't ideal.

**Additional context**
https://github.com/Rosalie241/GLideN64/blob/master/.github/workflows/build.yml#L198-L230
https://github.com/Rosalie241/GLideN64/releases/tag/github-actions

**Comment by ncipollo** [comment]
`v1` and `v1.8.9` now contain this feature. Thanks again for the PR!
