### ISSUE TITLE
Artifacts over 2147483647 bytes do not get uploaded

### ISSUE THREAD

**Issue by Ace314159** [ncipollo/release-action#110]
**Describe the bug**
When the artifact is over 2147483647 bytes large, it is not added to the release.

**To Reproduce**
1. Add a release using artifacts over 2147483647 bytes large.
2. The artifact is not added to the release.

**Expected behavior**

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v1

**Additional context**
I think this occurs because in `Artifact.ts`, the file is read using `readFileSync` which returns a `Buffer`, and there is a max size limit for `Buffer` objects.

**Comment by Ace314159** [comment]
This seems to be a limitation of GitHub itself, not of the action.

**Comment by rgl** [comment]
Oh this is a major bummer. For reference, GitHub mentions this sad situation at https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas:

> Storage and bandwidth quotas
> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

**Comment by mara004** [comment]
> Oh this is a major bummer. For reference, GitHub mentions this sad situation at [...]

2 GB for an individual artifact is actually huge.
Also, as you quoted, there is not limit on the total size of a release, which is astounding enough.

**Comment by rgl** [comment]
@mara004, sorry, but your comment is useless. obviously that depends on the use-case. anyhow, it does not matter, because this is a github limitation.

**Comment by mara004** [comment]
Well, the point is just that that limit (2 GB for free for an individual file) is quite high already, so I'd say wording like "major bummer" or "sad situation" is unjustified.
IMHO if you have such huge files you should be prepared to deal with hosting on your own.
