### ISSUE TITLE
Retries on asset uploadleads to "already_axists"

### ISSUE THREAD

**Issue by sheosi** [ncipollo/release-action#149]
While trying to upload a large asset, the connection may have problems (ECONNRESET) and when that happens the action will retry but since it is the same file GitHub says that it already exists. This happens even if removeArtifacts and allowUpdates are set to true.

**To Reproduce**
1. Setup the action to upload large files
2. Run the action
3. An ECONNRESET might happen
4. If we get the ECONNRESET GitHub returns: `{"resource":"ReleaseAsset","code":"already_exists","field":"name"}.`

**Expected behavior**
All the files being uploaded.

**Action container:**
 - OS: Linux Fedora

**Additional context**
You can see the error with an action file pretty minimal here: [](https://github.com/sheosi/dynawo/actions/runs/1475977075)

**Comment by ncipollo** [comment]
Hi!

Unfortunately I think this is out of scope for this action. I'm not really sure how we would be better able to gracefully handle this kind of error, especially if github thinks the file already exists in the asset storage. I think your best bet would be to set `artifactErrorsFailBuild` to `true` so you action will fail and you can update the asset manually.
