### ISSUE TITLE
Updating an existing release replaces its name and body

### ISSUE THREAD

**Issue by mladenbrankovic** [ncipollo/release-action#15]
When setting `allowUpdates` to `true`, the release's name and body will be replaced with default values (for example a list of commits for the body). It would be great if those settings/texts of an existing release could be preserved (either by default or via an input called `preserveTexts` for example).

Note that I did not set the `body` and `name` inputs.

**Comment by mladenbrankovic** [comment]
Sorry, my bad. The "close" button in the new GitHub app looks like a button to close the bottom drawer.

**Comment by ncipollo** [comment]
You can now omit the body and name for a release. This will preserve the values previously set on the release during an update.

```
omitBody: true
omitName: true
```
