### ISSUE TITLE
Add ability to add an asset label

### ISSUE THREAD

**Issue by MrAlex94** [ncipollo/release-action#150]
**Describe the solution you'd like**
Add the ability to use the `label` parameter for each [asset uploaded](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset--parameters).

**Describe alternatives you've considered**
Using cURL to [add the label](https://docs.github.com/en/rest/reference/repos#update-a-release-asset--parameters) after the upload has happened.

**Comment by ncipollo** [comment]
I think your alternative approach is actually the way to go. The artifact list can actually be a glob of artifacts, so associating a label with each gets really clunky in terms of action configuration.
