### ISSUE TITLE
Release author.

### ISSUE THREAD

**Issue by fabiocaccamo** [ncipollo/release-action#157]
**Is your feature request related to a problem? Please describe.**
When a new release is created the author is **github-actions[bot]** instead of my username.

**Describe the solution you'd like**
Is it possible to automatically set it to the repository owner or to have an option for doing it?

**Describe alternatives you've considered**
Any

**Additional context**

![IMAGE 2021-12-23 10:47:40](https://user-images.githubusercontent.com/1035294/147222101-ebe95c9f-e1d2-469d-9601-4f6bde2ef1f1.jpg)

**Comment by ncipollo** [comment]
I think if you provide your personal access token for `token` it will show up as you.
