### ISSUE TITLE
Bigger File Releases

### ISSUE THREAD

**Issue by MrVauxs** [ncipollo/release-action#163]
**Is your feature request related to a problem? Please describe.**
The feature is related to an issue of not being able to upload a zip above the maximum node.js buffer size (2 gigabytes).
![image](https://user-images.githubusercontent.com/32039708/147860559-6ea3254e-54e9-4765-9009-7397bf2c9b17.png)

**Describe the solution you'd like**
It seems that a feasible solution would be to replace `readFile` and `readFileSync` methods with `createReadStream` to support bigger files.

**Additional Context**
This is a great tool to automate releases with, and I wish this was implemented to support bigger files rather than having to move to other release actions that may not have the features this one has.

Related [stackoverflow thread](https://stackoverflow.com/questions/62934017/file-size-6003804160-is-greater-than-possible-buffer-2147483647-in-node) to this issue.

**Comment by ncipollo** [comment]
Do you have an example of an action which supports uploading large assets to a release? The octokit function I'm using for this doesn't look like it supports uploading the data via a stream, though I could be wrong: https://octokit.github.io/rest.js/v18#repos-upload-release-asset
