### ISSUE TITLE
It is recommended to add output variables

### ISSUE THREAD

**Issue by binge8** [ncipollo/release-action#173]
To facilitate the use of subsequent workflows, it is recommended to add output variables. Operation result: success or failure.
Thanks！

**Comment by ncipollo** [comment]
Sorry, I'm not sure what you mean. This action does have an output, see https://github.com/ncipollo/release-action#action-outputs.

If the action fails, I'd expect your workflow to fail as well (though there might be some way to continue if the action fails).

**Comment by ncipollo** [comment]
Here's an example in the workflow docs which outlines how to fallback to an alternative step if the previous one fails (if that's what you are looking for) - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-status-check-functions
