### ISSUE TITLE
Unable to resolve action "latest" in Action

### ISSUE THREAD

**Issue by ThePieMonster** [ncipollo/release-action#181]
**Describe the bug**
`Error: Unable to resolve action "ncipollo/release-action@latest", unable to find version "latest"`

**To Reproduce**

1. Setup a action with the following uses line instead of `@v1`
2. `uses: ncipollo/release-action@latest`
3. Run the workflow

**Expected behavior**
The latest version is used instead of receiving a error.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Latest

**Comment by ncipollo** [comment]
`latest` isn't a tag that this action uses. You should use `v1` to get the latest `1.x.x` version. You really wouldn't want to always pull the actual latest. If I ever make a `v2` at some point, there could be breaking changes which would 💥 your workflow.
