### ISSUE TITLE
error publishing the release in another repository, in this case the repository is public, it was created only to publish the releases

### ISSUE THREAD

**Issue by amed901107** [ncipollo/release-action#186]
**Describe the bug**
Error publishing the release in another repository, in this case the repository is public, it was created only to publish the releases

 uses: ncipollo/release-action@v1
      with:
       artifacts: "build/app/outputs/apk/release/*.apk"
       repo: ${{ secrets.REPO_PUBLIC }}
       token: ${{ secrets.RELEASES_TOKEN }}

**Expected behavior**
That the release of the application is published in that other defined repo

**Screenshots**
![image](https://user-images.githubusercontent.com/49206173/158035939-307ce35c-b925-4526-a4e9-efdc99ca6313.png)

**Comment by ncipollo** [comment]
The error message from github is indicating that the other repo is empty. I'm guessing you can't publish to an empty repo.
