### ISSUE TITLE
Releases Created By This Action Do Not Receive "Latest" Tag

### ISSUE THREAD

**Issue by Dartanman** [ncipollo/release-action#196]
**Describe the bug**
When you create a new release with this action, it does not receive the "latest" tag, unless there are no previous releases.

**To Reproduce**
1. Create a release with this action while already having a release.

**Expected behavior**
I expect the newest release to have the latest tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/18451479/162225619-f400bb70-b2a6-4c61-a986-0300d36543f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 100.0.4896.75

**Additional context**
You can see my workflow file here: https://github.com/Dartanman/Extrassentials/blob/dev/.github/workflows/maven_build_dev.yml
I did consider that marking the newer one as "Pre-Release" may be affecting it, so I tried without. Unfortunately, that did not fix the problem.

**Comment by ncipollo** [comment]
This is actually not something setup when you create a release. It's something GitHub is doing behind the scenes. Here's the rule-set it uses:

> The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.

From https://docs.github.com/en/rest/reference/releases#get-the-latest-release.
