### ISSUE TITLE
Add support for specifying previous_tag_name

### ISSUE THREAD

**Issue by gjkamstra** [ncipollo/release-action#198]
**Is your feature request related to a problem? Please describe.**
The GH Release note generation is unable to determine the right previous version for our release when pre-releases are made. 

**Describe the solution you'd like**
The GH Release note API has an option to override the previous release. That is a good workaround for now. We would like to have this option also exposed from this action.
The property is called previous_tag_name. See https://docs.github.com/en/rest/reference/releases#generate-release-notes-content-for-a-release 

**Describe alternatives you've considered**
Request GH to make changes to their previous version logic. That has been asked however by others, and GH is pointing to specifying the previous tag instead. See for example: https://github.com/github/feedback/discussions/6857 

**Additional context**
N.A.

**Comment by ncipollo** [comment]
Oh actually it looks like that request simply generates release notes that you can then use with the `create-release-endpoint`. So if you are feeling ambitious you could create an action which outputs the `name` and `body`, then we can input those into this action.

**Comment by marcofranssen** [comment]
Wouldn't it be nice to have a release note strategy in this action?

e.g.

When creating prereleases followed by an official release I would love to have all the release notes of the prereleases in there as well.

That would really be awesome. Hope you reconsider adding that to this action. I would love it.

**Comment by ncipollo** [comment]
I don't disagree that this would be useful, I just think it would be better represented as a separate action. A few reasons:
1. The inputs list for this action is already getting pretty crazy. In order for this to be useful I would think you'd want to expose all of the options on the endpoint (which would make the input list here even crazier)
2. Having it as a separate action would give you more flexibility. For example, if you were also keeping track of a changes in a separate change log (something many projects do) you'd be able to do that.

**Comment by framerate** [comment]
Just curious if anyone forked and made that separate action? I'd love for my release notes to not be affected by my nightly builds!

**Comment by edumserrano** [comment]
If anyone else comes across this issue, I've implemented a version of what @ncipollo [suggested](https://github.com/ncipollo/release-action/issues/198#issuecomment-1099210794) in this PR edumserrano/dotnet-sdk-extensions#734 for one of my repos.

It's in powershell but hopefully should be enough to give an idea of how you can implement this.
