### ISSUE TITLE
Release is from latest commit on master when building from another branch

### ISSUE THREAD

**Issue by l3laze** [ncipollo/release-action#20]
Hi,

I'm trying to setup automated build + release/update of the "latest" tag for [kcov](https://github.com/l3laze/kcov). It's almost working, but the created release is using the latest commit from master while the build is running on a different branch because I'm still testing...lol. I tried setting `commit: GITHUB_SHA` and it's still behaving the same. I'm sure it's something simple I'm missing, but I'm so tired from trying to work my new job that I can't figure it out.

Is this the designed behavior, or a bug?

**Comment by ncipollo** [comment]
Okay, cool - glad you worked it out!
