### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by PrateekKhatri01** [ncipollo/release-action#201]
**Describe the bug**
We started facing this issue from last 3 days. When we are trying to create release we are getting below error:

fatal: unsafe repository ('/github/workspace' is owned by someone else)

**Expected behavior**
Should create new release 

Below is the workflow:

- name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag:  ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

Please help on this issue.

**Comment by ncipollo** [comment]
I just double checked and the action is working fine for me in my test repo. As the error indicates, perhaps you are trying to run the action within a repo you don't have access to? Actions might be disabled at your organization / repo level.
