### ISSUE TITLE
After update, Error 403: Resource not accessible by integration

### ISSUE THREAD

**Issue by MarkEnverus** [ncipollo/release-action#208]
This issue was closed but it persists
[https://github.com/ncipollo/release-action/issues/129](url)
I'm facing the same issue w/ Github.com - i can't even use a personal token - if i do that I get the error "Error: Error undefined: Parameter token or opts.auth is required"

**Comment by ncipollo** [comment]
I don't think this is an issue in the action, it sounds like you might have an issue with your repo (was it forked?) or your workflow file is formatted incorrectly.

Checkout this issue which sounds similar: https://github.com/actions/toolkit/issues/465. The issue they had was that it was a forked repo and secrets aren't available in those repos.

**Comment by DNA-PC** [comment]
I'm a bit confused by this.

I'm using a fork, that is a fork repo from another of my repositories.
The only secret I can think of is `{{secrets.GITHUB_TOKEN}}`, but I thought each repo would have its own, why would it try to use the one from the source repo?

**Comment by dadair-aptiv** [comment]
Think the solution is this: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs. I had this same issue thinking it was the docker container. I needed to set the `contents: write` access. 

I haven't tracked down why this repo in the organization needed this set for its workflows. The other repos didn't need it.
```
name: ...

on:
  ...
permissions:
  contents: write

jobs:
  ...
```

**Comment by DNA-PC** [comment]
Why would there need to be a "write" permission? What's being written? I thought my workflow failed because it was trying to read the GITHUB_TOKEN from its source repository.

**Comment by dadair-aptiv** [comment]
From my understanding, it needs the `write` permission to create a release. So you have to write the release to the repo. Not 100% sure if that is though. Just what I am inferring on the testing i did. The documentation isn't there / clear.

**Comment by Vadorequest** [comment]
Thanks for bringing some context. I've tested and it works using your solution.

**Comment by scottw-kr** [comment]
Adding 

> Think the solution is this: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs. I had this same issue thinking it was the docker container. I needed to set the `contents: write` access.
> 
> I haven't tracked down why this repo in the organization needed this set for its workflows. The other repos didn't need it.
> 
> ```
> name: ...
> 
> on:
>   ...
> permissions:
>   contents: write
> 
> jobs:
>   ...
> ```

Confirm this works on a fork.

**Comment by ortegamarcel** [comment]
> You might want to double check the action settings in your repository. It's possible you don't have write access by default (Settings --> Action --> General --> Workflow permissions)

@ncipollo Thanks, that solved my problem.

**Comment by baydim** [comment]
GREAT INFO BROO

**Comment by dktapps** [comment]
I ran into this today because I'd pushed a tag for a commit that wasn't on any branch of my fork, but (presumably) was on the upstream. Once I pushed the offending commit to a branch on my fork, the action succeeded without any changes.
