### ISSUE TITLE
[usage question] actions fails with Input required and not supplied: upload_url

### ISSUE THREAD

**Issue by nofishonfriday** [ncipollo/release-action#231]
Hi,

I'm pretty new to GitHub actions so a little guidance would be appreciated.

My workflow yml (linked where I'm using your action):
https://github.com/nofishonfriday/pamplejuce/blob/193fecfcca9be2d5c2d77a8a9ee9ca75f94da145/.github/workflows/cmake_ctest.yml#L126

As can be seen in the [runs log](https://github.com/nofishonfriday/pamplejuce/actions/runs/2605463373) the artifacts are there, but the action fails with following output:

![action log](https://user-images.githubusercontent.com/7658194/177046243-b0f6b1d4-d7f1-4841-8967-fe9688fc2b6f.jpg)

What am I doing wrong? Thank you.

**Comment by ncipollo** [comment]
`upload_url` is not a valid input, please see the readme / action.yml for a list of inputs. Generally, if you have questions please direct them to the discussions tab so others can see answers & participate in the conversation.

**Comment by nofishonfriday** [comment]
Sorry, I was unaware that the discussions section is active here.
Will do, thanks.
