### ISSUE TITLE
Auto Release notes is not working

### ISSUE THREAD

**Issue by ajaychoudhary-hotstar** [ncipollo/release-action#234]
**Describe the bug**
We need to create a git hub release with auto-release notes. The following code, it is not added release notes automatically. 
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          name: ${{ needs.package.outputs.BUILD_VERSION }}
          prerelease: true
          tag: ${{ needs.package.outputs.BUILD_VERSION }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

**To Reproduce**
Using the following actions run:
Run ncipollo/release-action@v1
  with:
    allowUpdates: true
    generateReleaseNotes: true
    name: 22.07.07.0-1011
    prerelease: true
    tag: 22.07.07.0-1011
    commit: commit_id
    token: ***
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true

**Expected behavior**
The release should be created with auto-release notes

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ncipollo** [comment]
This seems to be working for me, see - https://github.com/ncipollo/actions-playground/releases/tag/untagged-95475364fc24e629593c.

Here's the config for the test repo: https://github.com/ncipollo/actions-playground/blob/master/.github/workflows/tag.yml#L29

A few notes:
- This isn't supported for update operations (github's update endpoint doesn't accept this parameter)
- There needs to be a previous version for it to diff against.
- There might be other scenarios where github won't generate anything. Take a look at their docs for details on the exact semantics.
