### ISSUE TITLE
commit action not working properly

### ISSUE THREAD

**Issue by itsankit-google** [ncipollo/release-action#242]
**Describe the bug**
When passing branch name as the commit according to the documentation but it is using git ref to create the tag instead of latest commit on the provided branch.
ref - https://github.com/ncipollo/release-action#notes

**To Reproduce**
```
allowUpdates: true
prerelease: true
replacesArtifacts: true
commit: develop
```

**Expected behavior**
A tag should have been created using the latest commit on the provided branch.

**Comment by ncipollo** [comment]
`commit` will only work if all of the following are true:
- The release doesn't exist yet (i.e this is a create and not an update operation).
- The tag you are trying to create doesn't already exist. See https://docs.github.com/en/rest/releases/releases#create-a-release (look for `target_commitish`).

This action, and the github API themselves, are really optimized around generating a release from a tag. If you want your workflow to always push to a specific tag I would just do that with a shell command prior to this action running (then use that tag to publish the release).

**Comment by itsankit-google** [comment]
> `commit` will only work if all of the following are true:
> 
> * The release doesn't exist yet (i.e this is a create and not an update operation).
> * The tag you are trying to create doesn't already exist. See https://docs.github.com/en/rest/releases/releases#create-a-release (look for `target_commitish`).
> 
> This action, and the github APIs themselves, are really optimized around generating a release from a tag. If you want your workflow to always push to a specific tag I would just do that with a shell command prior to this action running (then use that tag to publish the release).

Can we support overriding the release and tag?
