### ISSUE TITLE
Upload to existing release does not update tag

### ISSUE THREAD

**Issue by LordOfDragons** [ncipollo/release-action#243]
I'm using this action to update nightly pre-release builds besides release builds. The nightly pre-release build is correctly updated with new artifacts. The tag assigned to it though ("nightly" in my case) is not updated. It still points to the same commit where the first nightly pre-release has been created.

Can you add an option to force updating the release tag if existing?

Or is there another way to achieve this?

**Comment by ncipollo** [comment]
Yeah, github has a bunch of constrains around how that commit is used, it only is respected if the tag doesn't already exist. See my answer here: https://github.com/ncipollo/release-action/issues/242

Luckily - I think this use case should be pretty straight forward to achieve just using a shell command as a step before the release-action. For example `git tag -f <tag_name>;git push -f origin <tag_name>`.

**Comment by LordOfDragons** [comment]
That seems to work. Maybe this can still be added as an option to your action? Since right now I need to add an extra checkout step and an extra shell step to do this which I think many projects could benefit from.
