### ISSUE TITLE
In some cases, specifying tag may be required

### ISSUE THREAD

**Issue by andy5995** [ncipollo/release-action#250]
I wonder if this doesn't need a minor change.

https://github.com/ncipollo/release-action/blob/5ffcfca321b7176797b3ae28f57be783149725c0/README.md?plain=1#L30

 I just had a case where specifying the tag was required.

L21 of step Release AppImage

https://github.com/0ad-matters/0ad-appimage/runs/8177995527?check_suite_focus=true#step:6:22

**Comment by ncipollo** [comment]
`tag` is optional - as noted if this is omitted the action will attempt to utilize the tag from the git ref. The reason it's not present for you is that it looks like your workflow is running on a branch push. If you had it running on a tag push the action would be able to infer it from the ref.
