### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by tahirmt** [ncipollo/release-action#253]
**Is your feature request related to a problem? Please describe.**
From arm64 runners node12 support is dropped so we should update to node16

**Describe the solution you'd like**
The node version should be updated to node16

**Describe alternatives you've considered**
not possible

**Additional context**
node12 has reached end of life and GitHub doesn't support it for arm64 macOS runners

**Comment by ncipollo** [comment]
Merged to `main`. Will generate a new release once I get some dependbot updates merged.
