### ISSUE TITLE
Is it possible to specify the branch from which to generate the release?

### ISSUE THREAD

**Issue by Genereux-akotenou** [ncipollo/release-action#254]
Is it possible to specify the branch from which to generate the release?
I found your work very interesting. I used it to automate a process. I use the branch names with a pre-defined formatting as a tag to create my releases. The concern is that the generated release is done only on the main branch. The current content of the branch to which I push is not considered. Is there a way to specify the branch from which to generate the release? Thanks.

**Comment by ncipollo** [comment]
See readme, you can use commit and tag to generate a release (tag should be a unique tag name). Note this will only work once for given tag. Generally releases are optimized to work with tags tho, not branches. See git docs for pushing tags.

Also please use the discussion tab for future questions and conversation, issues are meant for reporting bugs and requesting features.
