### ISSUE TITLE
updateOnlyUnreleased defaults to true

### ISSUE THREAD

**Issue by farling42** [ncipollo/release-action#261]
**Describe the bug**
I just tried running a release against this action and it failed with an error about "updateOnlyUnreleased" being set on the action.

However that was not set because it is a new flag.

The documentation in your README says that this flag should default to FALSE (to keep existing behaviour).

**Comment by ncipollo** [comment]
oops, yeah I accidentally defaulted this to `true`. Fixing now.

**Comment by ncipollo** [comment]
This should be fixed on `main`, `v1` and `v1.11.0` if you re-run your action.
