### ISSUE TITLE
Generate release notes leading to invalid json response body

### ISSUE THREAD

**Issue by ashubisht** [ncipollo/release-action#262]
**Describe the bug**
Hi, I want to create release on merge of branch. I have set option generateReleaseNotes to true, but I am getting: 
`Error: Error 500: invalid json response body at https://api.github.com/repos/<group>/<project>/releases reason: Unexpected end of JSON input`

**To Reproduce**

I am using following script to create release:
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare release
        id: release
        run: |
          echo "::set-output name=VERSION::$(jq -r .version package.json)"
          echo "::set-output name=DATE::$(date +'%Y-%m-%d')"
          git tag $(jq -r .version package.json)
          git push origin $(jq -r .version package.json)
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.release.outputs.VERSION }}
          name: Release v${{steps.release.outputs.VERSION}} ${{steps.release.outputs.DATE}}
          removeArtifacts: true
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}

**Expected behavior**
It should successfully create release

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Browser Chrome
 - Version 106

**Comment by ncipollo** [comment]
This is working in my test repo - https://github.com/ncipollo/actions-playground/releases/tag/0.1.77. If I had to hazard a guess I would maybe say that your script which is setting the tag or version name is generating something invalid. Could you try just hard coding those value to see if it functions correctly.
