### ISSUE TITLE
How can I create a release in another public repo?

### ISSUE THREAD

**Issue by krupitskas** [ncipollo/release-action#27]
Hi! Currently Im trying to automate things and we are working in private repository. 
Im working on self updater, which should read latest tag version from the release, but it would be easier to do it without any personal access token, just with neighbour public repository.

**Comment by ncipollo** [comment]
Hi!
It's not currently possible to specify the repo you want the release to be created in. The action always assumes you want to create the release in the current repo. I could look into adding `owner` and `repo` as optional input arguments. 

> but it would be easier to do it without any personal access token

You will need the personal access token even if I implement this feature (I'm pretty sure). The github API calls require it. You can just save your personal access token in a secret though (see https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)

**Comment by krupitskas** [comment]
Thanks for quick response!

> You will need the personal access token even if I implement this feature (I'm pretty sure). 

I've just tested it with your repo:
`curl -i https://api.github.com/repos/ncipollo/release-action`

```

HTTP/2 200
date: Wed, 10 Feb 2021 14:03:32 GMT
content-type: application/json; charset=utf-8
server: GitHub.com
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With, Accept-Encoding
etag: W/"a23305e812d4161e756a4373bbcd0003b878cd9433f6bce5414566410a346a4e"
last-modified: Wed, 10 Feb 2021 04:20:34 GMT
x-github-media-type: github.v3; format=json
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
x-ratelimit-reset: 1612969360
x-ratelimit-used: 2
accept-ranges: bytes
content-length: 5648
x-github-request-id: 0686:3491:1473B57:16C0C54:6023E7B4

{
  "id": 204020546,
  "node_id": "MDEwOlJlcG9zaXRvcnkyMDQwMjA1NDY=",
  "name": "release-action",
  "full_name": "ncipollo/release-action",
  "private": false,
  "owner": {
    "login": "ncipollo",
    "id": 5712756,
    "node_id": "MDQ6VXNlcjU3MTI3NTY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5712756?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ncipollo",
    "html_url": "https://github.com/ncipollo",
    "followers_url": "https://api.github.com/users/ncipollo/followers",
...
```
The thing is, I don't want to keep personal access token and my nickname in my app as a string variable, because it easily can be reversed.

**Comment by ncipollo** [comment]
Different endpoints have different requirements around the access token. To create a release, you need an access token with push access to the repo. See https://docs.github.com/en/rest/reference/repos#create-a-release.

> The thing is, I don't want to keep personal access token and my nickname in my app as a string variable, because it easily can be reversed.

You can use github's secrets feature for this. Secrets are only accessible by the running action and once entered, can't be views or reversed. See https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by ncipollo** [comment]
I just updated v1.8.0 to allow for two new inputs: `owner` and `repo`. You can use these to generate the release in a different repo. As discussed above you'll need to add your personal access token as a secret and use that, the default one generated in the workflow environment will likely not have push access to other repos.
