### ISSUE TITLE
Example in readme is incorrect

### ISSUE THREAD

**Issue by XANi** [ncipollo/release-action#272]
this:

      - uses: ncipollo/release-action@v1
        name: Release
        with:
          artifacts: "bin/*"
          bodyFile: "body.md"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}

results in

![image](https://user-images.githubusercontent.com/147394/198953477-1a469851-07a8-4ce8-bc81-1c957dc32231.png)

this works

      - uses: ncipollo/release-action@v1
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "bin/*"
          bodyFile: "body.md"

**Comment by ncipollo** [comment]
The intent is to illustrate that you should provide the token via a secret, which is something well documented in the GitHub action docs. 

You can also omit the token and the action will use your default token.

**Comment by XANi** [comment]
Okay but when you do it as the doc shows it does not work

**Comment by chrisfentiman** [comment]
I ran into this same issue. Documentation should be runnable.
