### ISSUE TITLE
Documentation: Example

### ISSUE THREAD

**Issue by software-made-easy** [ncipollo/release-action#273]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I would be very happy if there was an example of how to build and package on multible os's and upload it to one release.

**Additional context**
Like [here](https://dev.to/eugenebabichenko/automated-multi-platform-releases-with-github-actions-1abg) but with this action instead of GitHub ones.

**Comment by ncipollo** [comment]
Sorry, but I think this use case is out of scope for this action's documentation. You can hit up the discussion tab though and see if other folks have examples of workflows which achieve this.
