### ISSUE TITLE
[action deployment]: deploy future versions twice, one as `latest` the other with corresponding tag

### ISSUE THREAD

**Issue by israpps** [ncipollo/release-action#277]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.
Simply upload your releases twice, one with the proper versioning, and other replacing `latest`

**Describe the solution you'd like**

**Describe alternatives you've considered**
there aren't alternative methods to make this

**Additional context**
this would allow consumers of this workflow to set the `uses` step to `uses: ncipollo/release-action@latest`, to maintain the usage of latest available version of this action, without polluting git history to update the version declared on the workflow each time

**Comment by israpps** [comment]
idea inspired on what https://github.com/marvinpinto/action-automatic-releases does

**Comment by ncipollo** [comment]
Thanks for the suggestion but I don't want to maintain a separate tag. `v1` is the latest stable release which you should be using if you want the latest and greatest.
