### ISSUE TITLE
Error: Error undefined: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by JulianMod** [ncipollo/release-action#279]
I'm receiving missing token error

My build.yml file:
`on: push
name: Test, Build and Release apk
jobs:
  build:
    name:
      Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          java-version: '11.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: master
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}`

**Expected behavior**
Create a Release APK should create apk

**Screenshots**
![image](https://user-images.githubusercontent.com/67909568/204797206-9a0bfca7-7fd0-4d9c-a6a2-f3d3d20e4bd5.png)

**Comment by ncipollo** [comment]
Looks like your token might be missing from secrets. Try removing the token input, by default the action will use the standard github runner token.

**Comment by JulianMod** [comment]
Unfortunately I got another one:
`Error: Error undefined: No tag found in ref or input!`
