### ISSUE TITLE
Can it actually push tags?

### ISSUE THREAD

**Issue by krupitskas** [ncipollo/release-action#28]
Hi! Im curious, can this release action actually push tags? 
Im using https://github.com/PaulHatch/semantic-version to calculate next tag version, and this would be great if release-action can push it.

**Comment by ncipollo** [comment]
That should work. Checkout the action arguments `tag` and `commit` in the readme - https://github.com/ncipollo/release-action/issues/28

If you have additional questions could you use the `Discussions` feature in this repo? That way the question and answer gets recorded somewhere for posterity.

**Comment by AraHaan** [comment]
I am having an issue where it thinks this tag is not valid: 
![image](https://user-images.githubusercontent.com/15173749/192881473-a4b94f49-fc71-4a01-acbe-0515b2667b3c.png)

Where I have the version to use for tagging a prerelease that is obtained from an action step.
