### ISSUE TITLE
Suspicious activity that suggests a threat actor used a Personal Access Token (PAT) associated with your account to access private repository metadata.

### ISSUE THREAD

**Issue by glensc** [ncipollo/release-action#285]
This ncipollo/release-action@v1 action caused GitHub support to revoke all my tokens and reset my password due to suspicious activity:
- https://github.com/eventum/eventum/pull/1238#issuecomment-1342236602

**Comment by ncipollo** [comment]
As far as I'm aware we are handling tokens as documented for github actions. Not sure what happened in your case, maybe try using the default action runner token instead of a personal token.

**Comment by glensc** [comment]
I'm using `github-token: ${{ secrets.GITHUB_TOKEN }}`:
- https://github.com/eventum/eventum/pull/1238/files

and that is the default runner token to my knowledge.

**Comment by ncipollo** [comment]
Hmm yeah I think that would be the default token (though if you just exclude it all together I use the default token the action library provides).

I'm not really sure what this could have been. If you provide your own personal token, then supply owner and repo inputs it would be possible for the action to check if a release already exists (needed for updating drafts), but failing that I don't think it pulls other info in from your account.

Are you positive it was the token provided to the action? The message which was linked seemed to just indicate a workflow name.

**Comment by ncipollo** [comment]
Hmm also possible that the personal access token you were using was an older one (they changed format recently), or it had overly broad access to your repos. Might be worth removing the token input and just using the default token (which only has access to the current repo).

**Comment by glensc** [comment]
I am not sure, but I can't check either as the tokens were deleted, no info about  them available. my next guess is that it could be it was token from travis-ci. but no jobs were run there over a year:
- https://app.travis-ci.com/github/eventum/eventum

since nothing to be done, it's fair to close the issue.
