### ISSUE TITLE
bodyFile input is not working?

### ISSUE THREAD

**Issue by FreePhoenix888** [ncipollo/release-action#287]
**Describe the bug**

**To Reproduce**
1. Pass `bodyFile` input to this action
2. See no body files pinned to release

**Expected behavior**
Body file must be pinned to a release

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: Version 107.0.5304.121 (Official Build) (64-bit)

**Additional context**
What I pass as bodyFile: https://github.com/linksplatform/Interfaces/actions/runs/3673984746/jobs/6211679727#step:3:9  
Note that the working directory is `cpp` therefore I use `Platform.Interfaces` instead of `cpp/Platform.Interfaces`.   
Output from `ls` : https://github.com/linksplatform/Interfaces/actions/runs/3673962999/jobs/6211631080#step:4:11
There is no body file: https://github.com/linksplatform/Interfaces/releases/tag/cpp_0.3.30

**Comment by FreePhoenix888** [comment]
@ncipollo , I would be happy to receive your help

**Comment by FreePhoenix888** [comment]
I do not see that `bodyFile` is used anywhere:
https://github.com/ncipollo/release-action/blob/main/src/Action.ts
https://github.com/ncipollo/release-action/search?q=bodyFile

**Comment by FreePhoenix888** [comment]
https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset

**Comment by ncipollo** [comment]
`bodyFile` is intended to be a markdown file which is rendered as the body of the release. It looks like you are passing it a directly, which isn't going to work. 

If you are trying to upload artifacts you should checkout the artifacts input (also note it can't handle directories directly so you will want to tarball / zip your directory before the action is run).

**Comment by FreePhoenix888** [comment]
> `bodyFile` is intended to be a markdown file which is rendered as the body of the release. It looks like you are passing it a directly, which isn't going to work.
> 
> If you are trying to upload artifacts you should checkout the artifacts input (also note it can't handle directories directly so you will want to tarball / zip your directory before the action is run).

Thank you :)
