### ISSUE TITLE
Artifact pattern did not match any files

### ISSUE THREAD

**Issue by FreePhoenix888** [ncipollo/release-action#288]
**Describe the bug**
Artifact pattern :platform.interfaces_0.3.37.zip did not match any files when `platform.interfaces_0.3.37.zip` file is presented

**To Reproduce**
1. Zip files with the name `platform.interfaces_0.3.37.zip`
2. Pass `platform.interfaces_0.3.37.zip` as `artifacts` input
3. See error
 
**Expected behavior**
Release with `platform.interfaces_0.3.37.zip` artifact to be created

**Additional context**
I echo the output of `ls` command in my action step that is executed right before this action: https://github.com/linksplatform/Workflows/blob/e7000a8786e2990c2f4ea2e19ff6c79952984385/.github/workflows/cpp.yml#L137-L141 and there we can see that this file is presented
Some lines later I pass that file as artifacts input https://github.com/linksplatform/Workflows/blob/main/.github/workflows/cpp.yml#L154
`ls` output: https://github.com/linksplatform/Interfaces/actions/runs/3677823942/jobs/6220326927#step:3:54
Error: https://github.com/linksplatform/Interfaces/actions/runs/3677823942/jobs/6220326927#step:4:26

**Comment by ncipollo** [comment]
I believe the working directories are different. What you are `ls`ing out looks like your cpp directory, but the action is going to treat your root as the working directory.

**Comment by ncipollo** [comment]
I think that only applies for run steps. Not sure if there is a way to globally set working directory.
