### ISSUE TITLE
Show files uploaded as artifacts

### ISSUE THREAD

**Issue by ilg-ul** [ncipollo/release-action#294]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'm successfully using this action to publish all binary xPacks (<https://github.com/xpack-dev-tools>) and everything is fine. But I wonder whether it would be possible to also list the files uploaded to the release as artifacts, right after the configuration, to allow an easy visual check of the action.

Possibly enabled with something like a `verbose: true` configuration option.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ncipollo** [comment]
The action actually does log out each artifact it uploads, but they are logged as debug logs to avoid spammy output. You can enable them via: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging

**Comment by ilg-ul** [comment]
If I understand it right, this extra logging is intended for debugging jobs; it applies for the whole job, and the result is available in the archive. This is less convenient for day to day use.

As for the _spammy output_, if the functionality is enabled explicitly via a configuration option, it cannot be considered spam.

In my case I publish about 12 files each time, and all the other steps are way larger, builds with tens of thousand of lines, so this would definitely not be considered spam.

**Comment by ncipollo** [comment]
I think I would prefer to utilize the debug logging here rather than adding a separate flag which affects log level. Please also note that if the upload fails those are printed as warnings (or failures depending on settings). So even if you don't have debug logging enabled you can see if something failed.

**Comment by ilg-ul** [comment]
Maybe my proposal of using a flag named `verbose` was confusing, I do not suggest to add a flag that affects the log level, logging is fine as it is, and enabling it using the GitHub environment variable is ok.

My proposal is related only to showing the files uploaded as artifacts; you can use a flag like `showUploaded`, or find a more inspired name.

**Comment by ilg-ul** [comment]
> So even if you don't have debug logging enabled you can see if something failed.

My purpose is not to see if something failed, but to see what was actually published.

My workflows use configurations like:

- <https://github.com/xpack-dev-tools/mingw-w64-gcc-xpack/blob/e6d365ad4fd92a8d7cebd4fb0af6567ada473b8c/.github/workflows/build-xbbmi.yml#L65>

In other words I prepare various files in the `deploy` folder, then publish all of them.

It would be useful to have a visual confirmation that the expected files were really published.

**Comment by ncipollo** [comment]
Sorry - to clarify it's not the naming convention I'm opposed to. I don't want to have multiple mechanisms to print out the artifacts. You can either enable debug logging or you could always fork the action and bump up the log level for that log.

**Comment by ilg-ul** [comment]
> I don't want to have multiple mechanisms to print out the artifacts. You can either enable debug logging...

Perhaps I'm not understanding your proposal properly. Can you be more specific on how to enable the debug logging only for this action, without affecting the other actions, which, in my case, are already very verbose?

**Comment by Hipska** [comment]
I would also love to see some extra information about the working of this action. Currently it says nothing.

I'm also not looking for debug level logging, just something a bit more simple things as easy as:
> Created release 'xxxx'.
> Updated release 'xxx'.
> Attached file 'xxxx'.
