### ISSUE TITLE
Option to skip if no tag present

### ISSUE THREAD

**Issue by olfek** [ncipollo/release-action#295]
When triggering a workflow on `push`, I need a way to skip this action if no tag is present.

This command ...

```
git tag --points-at ${{ github.sha }}
```

... tells us if there are any tags pointing at the checked out commit,
so maybe we can use this to perform a check?

Currently, in such as a case, I get this error:

```
Error undefined: No tag found in ref or input!
```

**Comment by ncipollo** [comment]
This is out of scope for this action, you could probably run this as a separate step, then skip the rest of the workflow if there is no tag tho.
