### ISSUE TITLE
Ability to get diff/changelog between two tags

### ISSUE THREAD

**Issue by varun-charan** [ncipollo/release-action#297]
**Is your feature request related to a problem? Please describe.**
I have a use case where I have a mono repo where multiple sub modules are residing. And each submodule is released with its specific version/tag. In your current action, the changelog picks the latest tag in the Git repo (can be for any submodule) and generates the changelog from that tag to the newly generated tag (post PR merge). What I need is to have the changelog compare two tags of that submodule only.

**Describe the solution you'd like**
There should be two inputs in the action - fromTag and toTag - which a user can use to explicitly mention the tags he wants the diff between. Default value of fromTag can be latest tag present in Git repo (same as it is today). Default value for toTag can be the value user provides under "tag" input. Or, default for these can be empty string.

**Comment by ncipollo** [comment]
That functionality is actually provided by github by their API, not something baked into the action itself. The action itself does nothing in terms of diffing (which is out of scope). You could add a separate step in your workflow to generate the diff, then pass to the action as the body.
