### ISSUE TITLE
请问这个问题要怎么解决？

### ISSUE THREAD

**Issue by 281677160** [ncipollo/release-action#30]
![QQ截图20210302170803](https://user-images.githubusercontent.com/66651997/109625263-11cff500-7b7a-11eb-8574-9cc0dffc486b.png)

请问一下红框里面的是什么问题？怎么解决？

下面是我的设置
![QQ截图20210302171245](https://user-images.githubusercontent.com/66651997/109625669-8efb6a00-7b7a-11eb-88ea-96821a455f43.png)

**Comment by ncipollo** [comment]
@281677160,
如果尝试上载文件大小为零的工件，则能够重现此错误。 您应该检查其余的操作，并确保生成的有效文件要作为工件上传。

**Comment by 281677160** [comment]
> @281677160,
> 如果尝试上载文件大小为零的工件，则能够重现此错误。 您应该检查其余的操作，并确保生成的有效文件要作为工件上传。
> 
> I am able to reproduce this error if I try and upload an artifact that has a file size of zero. You should check the rest of your action and make sure you are generating a valid file to upload as an artifact.

你好，感激你的回复，这个是一个MD5数值文件，有时候能正常上传的，但是会出现警告，有时候会出现错误上传不了

**Comment by ncipollo** [comment]
嗨，不客气！

我怀疑这意味着在某些情况下，您生成的MD5长度为0，这可能意味着您从其生成文件的文件丢失了。 为了进一步调试，也可以将这些文件也上传到操作中，这样，当发布操作生成这些警告时，您就可以查看它们。

如果您在此处查看，他们也遇到了类似的问题，这是文件大小为0的结果-https://github.com/octokit/octokit.net/issues/482#issuecomment-42150936 

Hi, your welcome!

I suspect this means there are scenarios where your generated MD5 is of 0 length, which might mean the file from which you are generating it is missing. To further debug, it might make sense to also upload those files to the action so you can take a look at them when when the release-action generates these warnings.

If you look here they were having a similar issue and it was a result of the file size being 0 - https://github.com/octokit/octokit.net/issues/482#issuecomment-42150936

**Comment by 281677160** [comment]
> 嗨，不客气！
> 
> 我怀疑这意味着在某些情况下，您生成的MD5长度为0，这可能意味着您从其生成文件的文件丢失了。 为了进一步调试，也可以将这些文件也上传到操作中，这样，当发布操作生成这些警告时，您就可以查看它们。
> 
> 如果您在此处查看，他们也遇到了类似的问题，这是文件大小为0的结果-[octokit/octokit.net#482 (comment)](https://github.com/octokit/octokit.net/issues/482#issuecomment-42150936)
> 
> Hi, you're welcome!
> 
> I suspect this means there are scenarios where your generated MD5 is of 0 length, which might mean the file from which you are generating it is missing. To further debug, it might make sense to also upload those files to the action so you can take a look at them when when the release-action generates these warnings.
> 
> If you look here they were having a similar issue and it was a result of the file size being 0 - [octokit/octokit.net#482 (comment)](https://github.com/octokit/octokit.net/issues/482#issuecomment-42150936)

非常感谢你，99%都能成功上传发布的，虽然是成功了，但是会出现警告，偶尔才会真正的发布不了，谢谢你的提醒，我把他都这个文件上传操作中跟发布同时进行，发布不了的时候可以对比

**Comment by ncipollo** [comment]
好的，太好了-一旦您捕获了引起问题的文件，我就可以帮助进一步调试。

我确实想指出另一件事。 如果操作正在更新现有发行版，则在上传工件失败的情况下不会失败。 因此，当您看到这些警告时，您的发行版实际上可能已附加了旧工件。 

Okay, great - I can help debug further once you've captured the files causing the issue.

I did want to point out one other thing. If the action is updating an existing release it won't fail if artifact fails to upload. So your release may actually have old artifacts attached to it when you see those warnings.
