### ISSUE TITLE
[Question] Does this update/overwrite the tag if it exists?

### ISSUE THREAD

**Issue by Minionguyjpro** [ncipollo/release-action#311]
Hello there, I have a question: does this update/overwrite the tag if it exists? If not, I would love to see a function to do so.

**Comment by ncipollo** [comment]
That is not the intent of this action. You can achieve that with a simple run step.

**Comment by Minionguyjpro** [comment]
> That is not the intent of this action. You can achieve that with a simple run step.

Could you give me an example? I need to make sure a tag is only deleted when a draft release exists. It may sound a bit complicated, but can't seem to find anything about it..., to make sure that public releases make sure the tag for that release is not deleted, and is deleted when it is a draft.

**Comment by ncipollo** [comment]
A release is associated with a tag, even if it's a draft so not sure I understand what you are after. If you want to delete the tag of the draft is closed you could google around for GitHub workflow triggers for release state changes, then delete the tag via a script when that happens.

**Comment by constgen** [comment]
Take a look at this https://github.com/marketplace/actions/delete-tag-and-release . Delete the tag before the release and it will be created again

**Comment by Minionguyjpro** [comment]
> @Minionguyjpro Take a look at this https://github.com/marketplace/actions/delete-tag-and-release . Delete the tag before the release and it will be created again. And you can even delete the release itself

Thank you for sharing!
