### ISSUE TITLE
Publish to marketplace

### ISSUE THREAD

**Issue by YunaBraska** [ncipollo/release-action#316]
**Is your feature request related to a problem? Please describe.**
When i create a release for my github action, then a flag is missing to also publish the release to the github marketplace

**Describe the solution you'd like**
I would like to have an option like `publishToMarketPlace` with values `true`|`false`

**Describe alternatives you've considered**
You are my hope, i have no alternatives.

**Additional context**
I am currently playing around with the releases on my github actions: https://github.com/YunaBraska/git-info-action/releases

**Comment by ncipollo** [comment]
I don't think this is currently possible with the github API. Publishing to the market place requires 2FA typically, so it's not something you could easily automate. See https://github.com/cli/cli/issues/5193#issuecomment-1036278907

Even if this were possible, I don't think it would be in scope for this action. I would probably split that out into a separate action (which could run after this one).
