### ISSUE TITLE
Add support for pre-parsing project before exporting

### ISSUE THREAD

**Issue by Malcolmnixon** [ncipollo/release-action#324]
**Is your feature request related to a problem? Please describe.**
Godot 4 is capable of handling gdscript circular references by generating a global_script_class_cache.cfg file in the .godot folder; unfortunately in these cases the project also loads the first time with errors. The solution appears to be to load the project once (with the errors) so it generates the script cache, then quit and reload the project a second time with the cache intact and everything works correctly.

**Describe the solution you'd like**
I would like a command-line option to perform this two-pass processing. This would probably be done by running godot to open A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
I don't see an easy way to trigger the two-pass outside of the action, as the action is responsible for both installing godot, and then running it once to perform the exports.

**Additional context**
N/A

**Comment by ncipollo** [comment]
I think you maybe posted in the wrong action, this action doesn't install Godot ;)
