### ISSUE TITLE
Error: Error 422: Validation Failed: check failed:\n  You're not authorized to create a tag

### ISSUE THREAD

**Issue by no-hands-hand** [ncipollo/release-action#332]
**Describe the bug**
No matter what tags I try, I am not able to create any releases via this (or any) Action. They give me a 422 error that says I am not authorized to create a tag. I am the owner of the repo, I created it myself. Full error:
Error: Error 422: Validation Failed: {"resource":"Release","code":"custom","field":"pre_receive","message":"pre_receive protected tag 'gflcraft-v0.5.8.2' check failed:\n  You're not authorized to create a tag"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}

**To Reproduce**
1. Go to [the repo](https://github.com/no-hands-hand/GFLCraft/actions)
2. Click on 'Run Workflow'
3. Input any version info

**Expected behavior**
I just want to create a release on workflow dispatch. This is not based on any random push, I want it to be manual.

**Screenshots**
![image](https://github.com/ncipollo/release-action/assets/47340636/9184be04-4029-4f4d-8608-0d550868900e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Latest Chrome versino

**Additional context**
I am just trying to make an easy updating and compiling of a modpack, I just zip up the files and publish the .zip to the release.

**Comment by ncipollo** [comment]
You need to make sure the action runner has permission to write to your repo. You also need to make sure it could actually create that tag (ie it doesn't already exist, and a user would have permissions to do so in your repo).

**Comment by ncipollo** [comment]
Sorry not sure what you need in your specific case. That error typically indicates that the action doesn't have permissions within the repo.
