### ISSUE TITLE
Release created via this action gets drafted if a git branch is updated

### ISSUE THREAD

**Issue by seppzer0** [ncipollo/release-action#336]
**Describe the bug**
After I've released a tag via this action, if I push any update on any of the branches of the repository, the release get automatically drafted, which should not happen.

**To Reproduce**
1. Create a release using this GitHub action;
2. Create a new branch from the one that was used to create a release (e.g., create `dev` from `main`);
3. Push any change to the new branch;
4. Observe that your release is now automatically drafted.

**Expected behavior**
Previously created release must stay undrafted and unchanged.

**Additional context**
I read the documentation on your GitHub action and did not find any related option that could be causing my case.

**Comment by seppzer0** [comment]
Found somewhat of a similar issue:
https://github.com/ncipollo/release-action/issues/317

However, my action does not even run for `dev` branch. However, if I push anything to the branch, the release gets drafted anyway.

**Comment by ncipollo** [comment]
Not sure this is the action doing this as opposed to the action. If the action isn't even running when a commit is pushed to the new branch I don't think it's the action. I'd recommend checking your repo settings to make sure you don't have a rule setup.

**Comment by seppzer0** [comment]
> ... If the action isn't even running when a commit is pushed to the new branch I don't think it's the action. I'd recommend checking your repo settings to make sure you don't have a rule setup.

Sounds sensible. However there are no specific rules in my repository whatsoever. It is public and has no rulesets on anything.

**Comment by ncipollo** [comment]
Could you send me a link to the repo with the issue?

**Comment by seppzer0** [comment]
Sure, here
https://github.com/seppzer0/s0nh_kernel

**Comment by ncipollo** [comment]
Yeah so this seems like the same github behavior as #317. I don't think there's anything we can do in the action about it, checkout the original thread in that issue for some discuss. 

Just want to reiterate this note from that thread in case it can help:

> Generally, GitHub releases work best when you have a tag already and create a release from that. You can probably simplify your workflow by having a step before the release action which creates and pushes the tag.
