### ISSUE TITLE
Is artifactContentType useful to set?

### ISSUE THREAD

**Issue by Hipska** [ncipollo/release-action#365]
Does the setting `artifactContentType` actually has any effect?

When using the most common example of `application/zip` for a ZIP file, this does not seem to be reflected in the icon on the actual release page:
<img width="228" alt="image" src="https://github.com/ncipollo/release-action/assets/228588/415637d0-c513-4693-8201-031acad09762">

So, is there any benefit of setting this parameter? Why not always use `raw`?

**Comment by ncipollo** [comment]
I verified this is being pass down into the github API, so not sure. The API docs make it sounds like it would be used but Github or octokit might have more logic around this to prevent misclassification of assets (which could be a security concern).

**Comment by Hipska** [comment]
I also tracked it down to the OctoKit. I see no benefit of specifying something else than `raw` are this point.

**Comment by ncipollo** [comment]
There might be some usecases where this is useful which are buried in documentation somewhere. I figure it's probably safer to leave it as an option in case someone has a legit need for it.
