### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by DavidSagan** [ncipollo/release-action#370]
**Is your feature request related to a problem? Please describe.**
Right now there are two **source code** assets automatically included in a release. For my particular application , these assets are not useful and in fact they can potentially be a source of confusion if someone downloads one of these assets.

**Describe the solution you'd like**
A solution would be to have an action input switch that can be set to disable inclusion of the source code assets.

**Describe alternatives you've considered**
I have not been able to come up with a suitable alternative.

**Additional context**
See <https://github.com/bmad-sim/bmad-ecosystem/releases/tag/20230917-0>. Here **bmad_dist.tar.gz** is the asset that everyone should download.

**Comment by ncipollo** [comment]
This is actually something Github is adding, I don't think there is a mechanism to turn that off or even delete after the fact (you can't even delete them via the Github UI).
