### ISSUE TITLE
`artifactErrorsFailBuild` doesn't seem to actually not create release

### ISSUE THREAD

**Issue by samip5** [ncipollo/release-action#382]
**Describe the bug**
When the action fails to match to any files, I think the `artifactErrorsFailBuild` being `true` should prevent an release being created but that's not the case.

**To Reproduce**
1. Use the workflow with something that generates an artifact
2. The artifact generation step for whatever reason fails
3. The release is created despite an error with matching any files

**Expected behavior**
I would have expected it to not create a release as told to when that flag is true.

**Screenshots**
![image](https://github.com/ncipollo/release-action/assets/1703002/e337b738-6dd4-4430-b4e2-52dc9080f67a)

**Additional context**
https://github.com/samipsolutions/vyos-build/actions/runs/6687837787/job/18169035562 (I have already manually deleted the release)

**Comment by ncipollo** [comment]
The release must be created to try and upload artifacts to it, so it will already exist before we could have failed. If you want to prevent the release from existing if the artifacts don't exist that should be done as a separate step in the workflow.
