### ISSUE TITLE
Truncate `generateReleaseNotes` when exceeding GitHub's API maximum length

### ISSUE THREAD

**Issue by realeinherjar** [ncipollo/release-action#387]
**Describe the bug**
Whenever you set `generateReleaseNotes: true` and have a release with a body that exceeds 125,000 characters you have an error in the GH Action

See an example at https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/6677611149/job/18147798020

**Expected behavior**
`release-action` should truncate with `...` to avoid exceeding the maximum char length.

Cc @apoelstra.

**Comment by ncipollo** [comment]
GitHub creates the release notes as part of the release creation process, there is no opportunity for action to intercept the contents and truncate. 

If this is an issue in you repo you can manually set the body yourself (generating via a script, etc).
