### ISSUE TITLE
Add custom body after generated release notes?

### ISSUE THREAD

**Issue by caendesilva** [ncipollo/release-action#397]
Hey, thanks for the super useful action!

I'm wondering if there is a way to add the custom body **after** the generated release notes, or if this is something you would consider supporting.

**Comment by ncipollo** [comment]
I don't think the GitHub API supports that. The docs indicate the body will always be prepended to the generated notes. 

If you can find another action which will pull down the release info, you could always generate release with automatic notes, then read the body, then update your release. That's a bit out of scope for this action though (that adds a fair amount of complexity just to change where body is placed).

**Comment by caendesilva** [comment]
That's what I figured, thanks anyways!
