### ISSUE TITLE
error: Error 404 A Discussion could not be created. Make sure you passed a valid category name

### ISSUE THREAD

**Issue by RolfMoleman** [ncipollo/release-action#398]
**Describe the bug**

`error: Error 404 A Discussion could not be created. Make sure you passed a valid category name`
 when discussion variable set to "Announcements" or "announcements"

**To Reproduce**

in workflow:

`- name: Create a GitHub release
        if: "!cancelled()"
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          body: ${{ steps.tag_version.outputs.changelog }}
          discussionCategory: "announcements"
          generateReleaseNotes: true
          makeLatest: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}`

**Expected behavior**

Announcements type of discussion to be created

**Screenshots**

Can provide if required

**Comment by ncipollo** [comment]
You need to make sure `Announcements` exists as a category in your repo - https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions

The API will fail if you try and pick a category which doesn't exist in the repo. I don't think announcements was always part of the default category set (this repo doesn't have it) so you probably need to add it manually in your discussion settings.

**Comment by ncipollo** [comment]
That field may also be case sensitive.

**Comment by RolfMoleman** [comment]
Hi @ncipollo it's definitely enabled on the specific repo, discussions are also definitely enabled on the same repo, where Announcements are a GitHub default.
I've tried upper and lowercase quoted and unquoted but get the same results.

**Comment by ncipollo** [comment]
Announcements is apparently a special discussion format and it won't work with the API. See response from github team here: https://github.com/goreleaser/goreleaser/issues/2304. I'll update the readme to mention this.

**Comment by ncipollo** [comment]
You might also be able to get it to work if you use a personal access token which has admin rights to the repo (as opposed to the default token). If you try that and it works let me know and I'll update the readme :)
