### ISSUE TITLE
[error]Validation Failed 

### ISSUE THREAD

**Issue by ca333** [ncipollo/release-action#4]
getting a cryptic error
```
##[error]Validation Failed
##[error]Node run failed with exit code 1
```

when attempting to release to a priv. git repo. I tagged the release and ensured access token is set properly. Maybe a more verbose err output would be a help too.

**Comment by ncipollo** [comment]
This is likely due to the release already existing. This error is coming directly from GitHub's octokit. I'll look to see if there's a way to get a more detailed error message.

**Comment by ncipollo** [comment]
@ca333,
A couple of updates:
- The action can now support updating a release. Set the `allowUpdates` input to `true` to set this up.
- Error output should now provide more robust error information. For example, if would let you know if the update already existed (if allowUpdates is off).
