### ISSUE TITLE
Add support for attaching full release notes (changelog) as release artifact

### ISSUE THREAD

**Issue by nicolaihenriksen** [ncipollo/release-action#405]
**Is your feature request related to a problem? Please describe.**
If a release has had a lot of contributions, the release notes (changelog) is capped at a certain number of characters (I believe).

**Describe the solution you'd like**
I would like an opt-in option to let the action create a `release_notes.md` artifact with the full content (i.e. not capped).

**Describe alternatives you've considered**
Alternatively the full release notes could be provided as an action output if outputs allow strings of that length (I haven't checked).

**Additional context**
I have seen #387 which indicates the truncation/capping does not happen in this action, yet I still see the `...` truncation in my recent release. Perhaps something has changed since.

**Comment by ncipollo** [comment]
These are generated by GitHub, not this action (using the releases api). It's likely they are truncating.

**Comment by nicolaihenriksen** [comment]
> These are generated by GitHub, not this action (using the releases api). It's likely they are truncating.

Thank you for the quick response. For information, if others stumble upon this issue, it seems like the full release notes is actually present when I edit the release, so it is probably just a visual thing in the UI that it truncates it.
