### ISSUE TITLE
Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by binge8** [ncipollo/release-action#406]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ncipollo/release-action@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by ncipollo** [comment]
👍 will take a look at getting that updated.

**Comment by Hipska** [comment]
I have the same when using `@v1`

**Comment by callicles** [comment]
Would be great!

**Comment by ray-peters** [comment]
@ncipollo is there anything we can do to help move this issue along?

**Comment by ncipollo** [comment]
@ray-peters, sorry about that - had approved the PR but it only just got merged down now. If you want to target one of your repos again `main` and test that would be 👌.

**Comment by ncipollo** [comment]
v1.14.0 and v1 versions should now be using node20.
