### ISSUE TITLE
how to get the tag description as body?

### ISSUE THREAD

**Issue by 1C0D** [ncipollo/release-action#407]
I'm using a script to create tags with a description from a prompt. How can I get this description to appear in the release (notes)?
for the moment I see 
Full Changelog: https://github.com/1C0D/obsidian-sample-plugin-modif/commits/1.0.0
but this is not compatible with another plugin using tag description. and only the last tag description is required

**Comment by ncipollo** [comment]
You should be able to do that pretty easily within your workflow. My initial idea here would be:
- to get the tag from github context (https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), 
- print out the tag message ( https://stackoverflow.com/questions/5358336/how-to-list-all-tags-along-with-the-full-message-in-gi
- Write that out to a file
- Pass that into the action via `bodyFile`

If you have additional questions or comments here, please open a discussion so others can benefit from the conversation.

**Comment by 1C0D** [comment]
Ok thks a lot for your answer. I will watch this tomorrow. for the moment I created a body.md in the workflow dir but I guess this is not the smarter way

**Comment by ncipollo** [comment]
That should work too (that's effectively what I was recommending)

**Comment by 1C0D** [comment]
could you past your first answer I opened a new discussion
