### ISSUE TITLE
Usage of `allowupdates`

### ISSUE THREAD

**Issue by samsmithnz** [ncipollo/release-action#412]
I'm a bit confused about how allowupdates works. 

I understand that it updates the body. To update the commit, I have to [update the tag](https://github.com/marketplace/actions/update-tag). All good there. 

How come the time stamp doesn't update? It seems confusing that I've updated the entire release (assets, tag, body), but the original timestamp still remains. What am I missing? 

![image](https://github.com/ncipollo/release-action/assets/8389039/6a3ebc4b-91fb-45c8-84a5-4bed83ca0e65)

**Comment by ncipollo** [comment]
This is something managed by GitHub, there is no mechanism to adjust the timestamp associated with the release (that I am aware of)


See api docs below:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release
