### ISSUE TITLE
Error 500: Request body length does not match content-length header

### ISSUE THREAD

**Issue by dhwz** [ncipollo/release-action#414]
After your action was updated today to v1.14.0 it always fails with the above error, after switching back to v1.13.0 it's working again.

If you search on Google for that error message it seems to be related to the change to Node20.

**Comment by ncipollo** [comment]
Could you provide more info on how to reproduce? Do you have a link to a repo which is experiencing this issue?

**Comment by dhwz** [comment]
Yes of course, this is the workflow which is executed on a regular base and it failed since this morning.
https://github.com/AmberELEC/AmberELEC/actions/runs/7795762806/workflow

**Comment by ncipollo** [comment]
Thanks! A few more follow up questions:
1. Is `main` a custom github runner?  (i.e runs on `main`)? If so, could you check that node is up to date?
2. Did you ever rename the `AmberELEC-prerelease` repo? From googling around it seems like there could be some issues with redirects, node 20 and octokit.

I've been testing this in my test repo and have so far been unable to reproduce (https://github.com/ncipollo/actions-playground)

**Comment by ncipollo** [comment]
Also I'm not seeing a job failure in that repo you linked. Do you have a specific job you can link me to, I want to see if there are any logs.

**Comment by dhwz** [comment]
1.) Yes it's our own server for the runner, I've to check what node version is on the runner, I've no access have to ask our admin.
2.) Indeed the repo was renamed previously but the URL above is the current name so it shouldn't have any redirects

This error is strange, now I tried to reproduce it to get you some logs but now it doesn't happen. It failed multiple times this morning.
I'll close the issue and reopen it when I have new information on this topic and also have a failed job.

**Comment by ncipollo** [comment]
Hmm quite weird. Thanks for the update!

**Comment by dhwz** [comment]
It's failing again today
https://github.com/AmberELEC/AmberELEC/actions/runs/7810284988

**Comment by ncipollo** [comment]
Were you able to check with your admin about what node version you are using? I wasn't able to reproduce, so I don't think there is much I can do until we narrow down what the root cause is.
