### ISSUE TITLE
Error undefined: Artifact pattern :wasp-Linux-x86_64.tar.gz did not match any files

### ISSUE THREAD

**Issue by Martinsos** [ncipollo/release-action#42]
Hi,
thanks for this great action!

I am having problem with artifact not being recognized, and I can't figure out what is the problem.

Here is the exact run that failed: https://github.com/wasp-lang/wasp/runs/2423559707?check_suite_focus=true#step:11:1 .

There is a step before that creates the file to be used as an artifact: https://github.com/wasp-lang/wasp/runs/2423559707?check_suite_focus=true#step:10:5 .

I tried adding step in between that does `pwd && ls` and it worked as expected: artifact is where it is supposed to be, and `pwd` is workflows working directory `waspc/`.

I am out of ideas how to fix this - any help is welcome!

**Comment by ncipollo** [comment]
Hmm, do you have a link to the workflow run where you included the `pwd` and `ls`? It looks like your artifact is being output to `/home/runner/work/wasp/wasp/waspc` which seems like it might be one level deeper than the working directory of the workflow (I think wasp/wasp). I'd try updating the artifact path provided to the action to be something like `waspc/xxx`.

**Comment by Martinsos** [comment]
Here is the workflow with `pwd` and `ls`: https://github.com/wasp-lang/wasp/runs/2423068468?check_suite_focus=true#step:11:1 .
It seems that `wasp/wasp/waspc` is ok! It is current directory, and artifact is visible in the current directory.

I tried adding `waspc/` in front of the path previously and that didn't help!

**Comment by Martinsos** [comment]
I also tried putting it in quotes, I tried going with '', nothing seems to work hm! Is it possible that release-action is not using the current working directory of the workflow? But in that case `waspc/` in front should help, and that also didn't help. Maybe it is problem because it is .tar.gz? But that doesn't make much sense and I saw it used in your example. Maybe the file somehow gets removed in the meantime? But that also sounds weird! I just have no idea how to go about this. Any advice on how to debug this?

**Comment by Martinsos** [comment]
I just tried smth different: I created dir `binpackages` and put the binary in it and then set artifacts to `binpackages/*` but that also didn't work: https://github.com/wasp-lang/wasp/runs/2425953902?check_suite_focus=true#step:10:6 .

**Comment by ncipollo** [comment]
Hi @Martinsos ,

I took a look at https://github.com/wasp-lang/wasp/runs/2423068468?check_suite_focus=true#step:11:1 (`pwd` and `ls` test) and it appears that the workflow isn't using the correct format when specifying the artifacts. That input expects a string which contains a comma delimited list of paths (ex- `"artifact.png,output/*.txt"`).

I'm not sure what the issue in the original workflow is. Here's a few things you can try:
- Enable workflow debugging. In this mode the action will print out some additional logs. See https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging
- Try simplifying the input into the action. Rather than using a variable to generate the path just hardcode it. If that functions correctly then there may be a formatting issue when you are generating the path.

I'll double check and make sure there isn't an issue uploading tarbarlls and let you know if I find anything.

**Comment by ncipollo** [comment]
Hmm, yeah I added a tarball to one of my test repos and it seemed to function correctly:
- Link to workflow: https://github.com/ncipollo/actions-playground/blob/master/.github/workflows/tag.yml#L16
- Resulting release: https://github.com/ncipollo/actions-playground/releases/tag/0.0.71

**Comment by Martinsos** [comment]
I just modified the workflow so it creates a file `test.txt` and uses that as an artifact, but that also doesn't work!
https://github.com/wasp-lang/wasp/runs/2430047028?check_suite_focus=true#step:11:14 .

Maybe problem is in working directory? Could you try setting `defaults.working-directory` to some dir in your repo?

**Comment by Martinsos** [comment]
Ok, this one, where I set artifact to `waspc/test.txt` actually passed! https://github.com/wasp-lang/wasp/runs/2430072429?check_suite_focus=true .

**Comment by Martinsos** [comment]
Ok, finally got it working properly with real artifacts: https://github.com/wasp-lang/wasp/actions/runs/782138880 .

Conclusion: it seems that paths to artifacts are not considered to be relative to the working directory, but to the root of the repo instead! Therefore, I had to add `waspc/` in front of the artifact path. I don't think this is expected behaviour -> you say in your docs that working directory is taken into consideration, right?

**Comment by ncipollo** [comment]
I think when you are setting the working directory via defaults, that is only in regards to shell commands you `run` (i.e the bit you have here - https://github.com/wasp-lang/wasp/actions/runs/779107717/workflow#L11). It doesn't impact third party actions.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

**Comment by Martinsos** [comment]
You are right! Sorry for all the confusion. I was sure I read at some point that artifacts are relative to the working directory, but it might be that I read that in some other repo, I certainly can't find it here. And as you said, current working directory option seems to be made with shell in mind, not all the actions.
Thanks, closing the issue!

**Comment by flymg** [comment]
got a similar error, for me it was the fact, that "artifacts" in this action mean "files" and not the github provided artifacts.
So if the file is not there in the run, this action leaves you with the pattern error.
>Artifact pattern did not match any files
