### ISSUE TITLE
[question] separate repo releasing

### ISSUE THREAD

**Issue by nerdCopter** [ncipollo/release-action#44]
How can I use `repo` parameter to release to a different repository?
Testing shown that seemingly only the repo name is required (not `org/repo`).
I receive ` Error: Error 403: Resource not accessible by integration` which is probably due `${{ secrets.GITHUB_TOKEN }}` is the wrong thing to use; however, i'm unsure what config/secrets to use for a github organization (not personal repo).

**Comment by ncipollo** [comment]
A few notes:
- Make sure you provide both the `owner` and `repo` inputs (a repo will be in the format `owner/repo`). 
- I think as long as you have access to repos in the organization your personal access token should still work. See this link for setting that access token up (make sure you provide repo access): https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
- If the organization has SSO enabled, make sure you enable that on your token.

If you have additional questions please use the discussions tab of this repo. It looks like there is already an open discussion in there on this topic: https://github.com/ncipollo/release-action/discussions/41
