### ISSUE TITLE
Suddenly upload of artifact fails with "already_exists","field":"name"

### ISSUE THREAD

**Issue by martinrotter** [ncipollo/release-action#444]
**Describe the bug**

I started getting error:

> Error: Error undefined: Failed to upload artifact rssguard-devbuild-a46adaba6-lite-win7.exe. Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}

I use the action in this repository, see that all was working and suddenly, new commits fail, even if no change in yml file was done.

https://github.com/martinrotter/rssguard/actions

Here is how release-action is called:

https://github.com/martinrotter/rssguard/blob/master/.github/workflows/rssguard.yml#L87

Do you have any idea why this error might be happening? It seems like there is some problem with the artifact/file with the name already existing, but to me it seems that artifacts in fact do have uniques names:

```
Run actions/download-artifact@v4
Found 8 artifact(s)
No input name or pattern filtered specified, downloading all artifacts
An extra directory with the artifact name will be created for each download
Preparing to download the following artifacts:
- RSS_Guard-macOS-Qt6 (ID: 1539922311, Size: 252185111)
- RSS_Guard-macOS-nowebengine-Qt6 (ID: 1539921808, Size: 63779048)
- RSS_Guard-Linux-Qt5 (ID: 1539921386, Size: 194805024)
- RSS_Guard-Windows-Qt6 (ID: 1539913756, Size: 291800388)
- RSS_Guard-Linux-nowebengine-Qt5 (ID: 1539911455, Size: 102403035)
- RSS_Guard-Windows-nowebengine-Qt6 (ID: 1539907124, Size: 91871755)
- RSS_Guard-Windows-Qt5 (ID: 1539902825, Size: 149142844)
- RSS_Guard-Windows-nowebengine-Qt5 (ID: 1539899952, Size: 68447069)
```

**Comment by martinrotter** [comment]
I enabled debug logging but no actual filenames are printed anywhere which is weird.

https://github.com/martinrotter/rssguard/actions/runs/9281813440/job/25539340050

I checked manually in each separate job and see no duplicated.

**Comment by ncipollo** [comment]
Hmm I don't think that enabled debug logging. If you look in my test workflow which has debug logging enabled via a secret you'll see tons of debug logs across the different steps: https://github.com/ncipollo/actions-playground/actions/runs/8882945290/job/24388719078

**Comment by martinrotter** [comment]
You are right! I had to add repository variables. Apparently variables put directly in flow YML file was not enough. Thanks.
