### ISSUE TITLE
Allow for more verbose output/errors

### ISSUE THREAD

**Issue by ghostbuster91** [ncipollo/release-action#461]
**Is your feature request related to a problem? Please describe.**

At $work we got following error from the plugin:
```
Run ncipollo/release-action@v1
  with:
    tag: abcd
    makeLatest: true
    body: <<redacted>>
    generateReleaseNotes: false
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
    skipIfReleaseExists: false
    token: ***
    updateOnlyUnreleased: false
Error: Error 500: 
```

This is the entire output. 

**Describe the solution you'd like**

Based on the output it is impossible to say at which step the plugin failed. Though it must have been before making the tag as there is no `abcd` tag. 

First, it would be great to have more details about the error. 
Second, maybe a verbose flag could be introduced that would print on stdout actions that the plugin is performing.

**Describe alternatives you've considered**

Pray for the error not to happen again.

**Comment by ncipollo** [comment]
Looks like that might be cropped? In any case if you enable debug logging you will get more information. Good around for the GitHub docs for that (you set a variable in the workflow which increases log level).
