### ISSUE TITLE
Log the action version

### ISSUE THREAD

**Issue by jsphstls** [ncipollo/release-action#471]
**Is your feature request related to a problem? Please describe.**
It is not possible to tell which version of this action was used during a workflow run. A tag can be specified, but that tag may resolve to a more specific version.

**Describe the solution you'd like**
Log the exact version of this action that was used during the run.

**Describe alternatives you've considered**
The version could be inferred by examining the tags in this repository vs the date of the run.

**Additional context**
The version could only appear when debugging if desired.

**Comment by ncipollo** [comment]
You should be able to see the yaml with every workflow run in GitHub. That contains the version of the action, does that not get you what you need or am I misunderstanding?
