### ISSUE TITLE
optionally exclude source code

### ISSUE THREAD

**Issue by fenicento** [ncipollo/release-action#473]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to only release part of the repo, or generated files / folders (e.g. "dist.zip"). At the moment I see no options to exclude the entire source code of the repo, it gets added by default.

**Describe the solution you'd like**
An optional "exlude-source" flag would suffice.

**Describe alternatives you've considered**
I tried using "removeArtifacts" before specifing the files I want to include, with no effect.

**Additional context**

**Comment by ncipollo** [comment]
I do not believe this is something GitHub supports via the API (or even at all).
