### ISSUE TITLE
Updating existing release seems to ignore `makeLatest`

### ISSUE THREAD

**Issue by dktapps** [ncipollo/release-action#483]
**Describe the bug**
As per title.

In [this repo](https://github.com/pmmp/PHP-Binaries), my workflows are updating `pm5-latest`, `pm5-php-8.2-latest` and `pm5-php-8.3-latest` releases on every build.

I have `makeLatest` set to `false` for everything except `pm5-latest` which has it set to `true` (confirmed in build logs).

However, `pm5-php-8.3-latest` always seems to get marked as latest anyway. This is even after I've manually set a _different_ release to latest before the action updated it.

**To Reproduce**
1. Have the action update non-latest release with `makeLatest: false`
2. Notice that it still gets marked as latest, I guess? I haven't tried to reproduce this in a different repo.

**Expected behavior**
`makeLatest` should be respected when updating releases

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
Example build log: https://github.com/pmmp/PHP-Binaries/actions/runs/12142324062

Check the `PHP 8.2 / Publish binaries` and `PHP 8.3 / Publish binaries` jobs.

**Comment by ncipollo** [comment]
See https://github.com/ncipollo/release-action/issues/466. I don't think false will definitely prevent that release from being marked as latest. Docs are vague but I'm guessing Github always wants a latest release and will take some liberties if there isn't an obviously marked one which is recent. The action is pretty much just passing this option to Github directly so I don't have much control over the behavior here.
