### ISSUE TITLE
missing 'upload_url' action output for advanced uses

### ISSUE THREAD

**Issue by jens-maus** [ncipollo/release-action#50]
**Is your feature request related to a problem? Please describe.**
This release action seems to be a perfect drop-in replacement for the recently archived/obsolete https://github.com/actions/create-release release action. However, the `upload_url` action output parameter seems to be missing which hinders use in more advanced usage scenarios.

**Describe the solution you'd like**
Would be great if this action could implement `upload_url` as an integral action output parameter so that in advanced workflows user can add release assets using other actions.

**Comment by ncipollo** [comment]
Working on publishing a release now! I added the outputs the `create-release` action had (id, http_url, and upload_url). Thanks for the feature request!
