### ISSUE TITLE
artifactErrorsFailBuild still creating release/tag even with failure

### ISSUE THREAD

**Issue by maxisme** [ncipollo/release-action#54]
**Describe the bug**
I have this in my CI:
https://github.com/maxisme/notifi/blob/3150b7dbed44a3d46553b065bbab8ea35bc0af6f/.github/workflows/ci.yml#L261-L270

I am getting this error:
https://github.com/maxisme/notifi/runs/2655999641?check_suite_focus=true

Yet it still created the release and tag (since deleted)

**Comment by ncipollo** [comment]
That error indicates one or more of the artifacts you are providing to it are directories. I think you need to tweak the path you are providing to the action (ex- `"${{steps.download.outputs.download-path}}/notif/*"`).

It might also be worth checking this issue out: https://github.com/ncipollo/release-action/issues/53#issuecomment-846029817 . It includes some tips on tweaking the output of the download artifact to get more predictable output.

**Comment by maxisme** [comment]
Hey, Yes - sorry I know why the error is happening - just bringing to your attention the fact the release was still created.

**Comment by ncipollo** [comment]
Ah, I see. Thanks for the clarification. Unfortunately the release needs to be created before we could get those errors back from the API. I could probably add some pre-checking to make sure an artifact isn't a directory but that would only cover that specific case - you'd still potentially run into this scenario if the artifact upload failed for some other reason.

**Comment by ncipollo** [comment]
Created an enhancement to add this specific check: #55

**Comment by SpoonOfDoom** [comment]
Is it possible to check if the file is there in a more general way? For example I messed up a filename, so the file could obviously not be uploaded. However, a release was still created.
Something like "isn't a directory && file exists" should be able to catch both?
