### ISSUE TITLE
Add optional input for Asset Label

### ISSUE THREAD

**Issue by WhiteFruit** [ncipollo/release-action#57]
I'd like to have the option to label the artifact being uploaded as a release asset to have a consistent UI display name across builds, while keeping the file name itself unique for each build.

I've considered simply using the "Update a Release Asset" endpoint to patch it just after uploading, but being able to do it with this action is preferred.

Thanks for your time.

**Comment by ncipollo** [comment]
I think that might be out of scope for this action. Currently the artifacts may be provided via a glob path which means their names may not even be known ahead of time. I'm not sure how you would cleanly provide a label per artifact.

This seems like something which would be better achieved via a separate action / workflow step which could be customized directly to your usecase.

**Comment by WhiteFruit** [comment]
Ah. Their names not being known ahead of time is why I'd like to have the option of a consistent label. I hadn't considered the difficulty of supplying a unique, meaningful label for the case of _multiple_ artifacts picked up by a glob, though - only a single one. 

I'm unable to think of a clean way to handle that either, so I'll call this closed. I greatly appreciate your work and response time.
