### ISSUE TITLE
Use a bot to update your GitHub Action workflows

### ISSUE THREAD

**Issue by HonkingGoose** [ncipollo/release-action#66]
**Is your feature request related to a problem? Please describe.**

I see that your GitHub Action workflow files are using outdated versions.
You can automate updating these versions with Dependabot.

Example, your `build.yml` file uses a old version of `actions/checkout`:

```yml
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
```

The latest stable version of `actions/checkout` is `@v2` 😉.
See: https://github.com/actions/checkout/releases

**Describe the solution you'd like**

Create a Dependabot config file that tells Dependabot to update Github Action workflow files with a PR.

**Describe alternatives you've considered**

Use Renovate bot to get workflow updates (and for other dependencies if you want).
The benefit of Renovate bot is that it can automerge the PRs, so you're not doing so much manual work.

You'd need to install the Renovate bot app into your GitHub account and give it permission to access this repository.
If you don't want to install an app, you can use Dependabot. 😉 

**Additional context**

I'm wiling to create the Dependabot config file or the Renovate bot configuration file.

**Comment by ncipollo** [comment]
Hi @HonkingGoose,

This is an interesting proposal! Could you supply an example Dependabot config which would trigger pull requests to update the github workflow?

Generally I am trying to keep this project somewhat stable. That is to say changes are typically additive and non-destructive. As such I'd be a little hesitant to have a bot automatically be updating dependencies. If Dependabot can be automated to propose these changes, and the scope of these changes can be configured, I think this might be a neat project optimization though.
