### ISSUE TITLE
Mention scope for the GitHub Token

### ISSUE THREAD

**Issue by aliasgarlabs** [ncipollo/release-action#69]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for this super useful action! Can we please include the scope required for the GitHub Token for the correct execution of this action in the README file? I think this can help people in giving just the right scope to the step :) Thanks!

**Describe the solution you'd like**
Mention minimum scopes it needs to create a release and upload the artifacts... 

**Describe alternatives you've considered**
Guess the scope it needs and try if it works.. 

**Additional context**
None.

**Comment by adeptex** [comment]
Hi there, thanks for your great work on this GH action! 

To add info to this issue:

[The readme](https://github.com/ncipollo/release-action/blob/main/README.md#action-inputs) indicates that `token: (Required) The GitHub token. Typically this will be ${{ secrets.GITHUB_TOKEN }}.`

In my case, not providing a value at all for the token works fine, and publishes the release as `github-actions` user. I'm not sure that the token value is strictly speaking required, as indicated.

Best regards

**Comment by ncipollo** [comment]
Updated readme to indicate the action requires `repo` scope access.
