### ISSUE TITLE
Release is from latest commit on master when building from another branch if latest commit is the same

### ISSUE THREAD

**Issue by snuyanzin** [ncipollo/release-action#81]
**Describe the bug**
The issue is a specific case of https://github.com/ncipollo/release-action/issues/20

**To Reproduce**

1. prerequisite 2 different branches (let's say master and branch1)
2. git cherry-pick of the latest commit from master to branch1
3. try to create release for branch1
4. in reality the release is created based on master instead of branch1

**Expected behavior**
Need to be able to create release for the specific branch

**Comment by ncipollo** [comment]
Hey,

I have a couple of follow up questions:
1. Do you have a link to the repo in which you are experiencing this issue? If not, could you provide your workflow?
2. Are you providing the `commit` input? By default the github API will create a tag from your primary branch if you do no provide it with a branch. You can override this behavior by providing a `commit` input, which I then pass into the API via `target_commitish` (see https://docs.github.com/en/rest/reference/repos#create-a-release).

**Comment by snuyanzin** [comment]
unfortunately the repo is a private repo of one organization.

Anyway the proposed solution with `target_commitish` seems working, thank you!
