### ISSUE TITLE
Error 500 when branch name contains emoji  

### ISSUE THREAD

**Issue by Pushpavel** [ncipollo/release-action#88]
Pushing commits on a branch that contains emoji on its name causes Error 500.

**Expected behavior**
Should Create Draft Release without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/53726418/125193920-95a69600-e26c-11eb-8ea5-20c76a1c7c07.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/53726418/125194045-2bdabc00-e26d-11eb-9ba7-8267489a4759.png)

**Comment by ncipollo** [comment]
Hi @Pushpavel ,

I don't think this is going to be fixable within the action, I just tried to create a release targeting a branch with emoji using the Github UI and I similarly received a 500 error on the site (though strangely enough it seemed to have created the tag).

**Comment by Pushpavel** [comment]
Thank you @ncipollo, I'll just avoid using Emojis for branch names from now on.
