### ISSUE TITLE
Create a release without a tag or running on tag

### ISSUE THREAD

**Issue by CarlosEsco** [ncipollo/release-action#91]
Maybe I am misreading and don't see the option, but i would like to run this in a manual job, that creates a draft of the release, where the repository has not been tagged yet with the new version.  Similar to how the github ui allows you to prep a release without tagging.

**Comment by ncipollo** [comment]
Hi @CarlosEsco,

Unfortunately Github requires that a tag is associated with a release (even a draft release). See the API documentation here: https://docs.github.com/en/rest/reference/repos#create-a-release .
